### PR TITLE
Allow module to enable service, but not manage it.

### PR DESCRIPTION
**Pull request by matheuslcruz**
When passing undef to service_ensure, it's ignored and assumed the default value of param, which is "true". When default value of $wildfly::params::service_ensure is undef, this module become more flexible because it's able to enable the service but not manage it.

### CODE REVIEW

**Comment by jairojunior** [comment]
Sorry, but I'm failing to see your intent here.

Couldn't you just?

```puppet
class { 'wildfly':
  service_ensure => false, #or 'stopped'
}

**Comment by matheuslcruz** [comment]
If service_ensure is false or stopped, then puppet agent will try to stop
the service. If true or running, it will try to start the service. I don't
want anyone of these behaviors. I need to stop the service - to deploy .ear
for example - and then restart the service. With ensure = undef, a manual
management of the service would be able. The problem is when I pass undef
to ensure_service. In this case puppet assumes the default value, which is
true.

Em 14/01/2017 17:01, "Jairo Junior" <notifications@github.com> escreveu:

**Comment by jairojunior** [comment]
I see your point.

I'd like to offer you two options, since the change you proposed will break the behavior for current users:

1 - Couldn't you use `wildfly_restart` for your scenario? You could have:

```puppet
wildfly::deployment { 'myapp.ear' :}
~>
wildfly::restart { 'restart after deploy':
```

2 - If you really can't manage Wildfly service with this module we could have something like `manage_user` parameter, but for service (`manage_service`), that defaults to true, but if it's set to false, service resource won't be declared:

Something like this: https://github.com/biemond/biemond-wildfly/blob/master/manifests/prepare.pp#L6 but here: https://github.com/biemond/biemond-wildfly/blob/master/manifests/service.pp#L38

**Comment by jairojunior** [comment]
Closed for lack of contact. If you still need this, feel free to reopen or open an issue.

**Pull request closed without merging**
