### PR TITLE
qualify variables to make templates work

### PR DESCRIPTION
**Pull request by ulamela**
Looks like pull request #61 reverted changes done in #30 , so now template is filled with empty values.

### CODE REVIEW

**Comment by jairojunior** [comment]
Oh, sorry. Probably my bad. Which version of puppet are you using?

**Comment by ulamela** [comment]
[root@gml-puppet production]# puppet --version
4.2.1

**Comment by smbambling** [comment]
@ulamela , also looks like the standalone.conf.erb template needs patched in a similar fashion.  Would you mind adding these changes to your PR.

````
sed -i "s/@/scope['wildfly::/g" standalone.conf.erb
sed -i "s/ %>/'] %>/g" standalone.conf.erb
````

````
if [ "x$JAVA_OPTS" = "x" ]; then
   JAVA_OPTS="-Xms<%= scope['wildfly::java_xms'] %> -Xmx<%= scope['wildfly::java_xmx'] %> -XX:MaxPermSize=<%= scope['wildfly::java_maxpermsize'] %>"
   JAVA_OPTS="$JAVA_OPTS <%= scope['wildfly::java_opts'] %>"
else
   echo "JAVA_OPTS already set in environment; overriding default settings with values: $JAVA_OPTS"
fi
````

**Comment by smbambling** [comment]
:+1:  to these changes, any change on getting them pulled in soon ?

**Comment by ulamela** [comment]
@smbambling, updated as requested plus changed to use 'lookupvar' function to support Puppet 2.7 (to support Puppet 2.7.x as specified on Forge module's page).

**Comment by smbambling** [comment]
@ulamela, looks good to me...hopefully this will get approved soon.

**Comment by biemond** [comment]
Thanks all :+1: 

Here we go, I will do some testing on puppet 4.2 and 3.8

**Pull request merged**
