### PR TITLE
New features

### PR DESCRIPTION
**Pull request by jairojunior**
There are two file()[1] in setup that I'm using Puppet 3.7 syntax and I was unable to port to a previous version in my vagrant environment

Can you take a look?

[1] http://www.unixdaemon.net/tools/puppet/puppet-3.7-file-function.html

### CODE REVIEW

**Comment by biemond** [comment]
Very nice,

Do you know how to solve these execs , so it doesn't execute every time

==> default: Info: Applying configuration version '1428416221'
==> default: Notice: /Stage[main]/My_wildfly/Wildfly::Standalone::Messaging::Topic[DemoTopic]/Wildfly::Util::Cli[DemoTopic]/Exec[DemoTopic]/returns: executed successfully
==> default: Notice: /Stage[main]/My_wildfly/Wildfly::Standalone::Messaging::Queue[DemoQueue]/Wildfly::Util::Cli[DemoQueue]/Exec[DemoQueue]/returns: executed successfully
==> default: Notice: /Stage[main]/My_wildfly/Wildfly::Standalone::Deploy_from_url[https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war]/Exec[Deploy https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war]/returns: executed successfully

Also the module install uses a tar.gz file. Can we use the jar or this url https://jdbc.postgresql.org/download/postgresql-9.4-1201.jdbc4.jar instead of using tar.gz or is this a special zip file you can download somewhere.

Thanks

**Comment by jairojunior** [comment]
Topic and Queue uses wildfly-cli-wrapper because JBoss-CLI scripts can't easily be idempotent, in other words, I always have to query for the current state before execute an action. The exec is begins executed, but it doesn't doing nothing. It's probably a bad practice, but I thought a custom type would be a Sledgehammer for a fly.

Deploy uses a ruby script for the same reasons. We need to verify deploy target file SHA1SUM to see if we need to redeploy.

Module install needs a directory structure with org/postgresql/main containing the jar and module.xml. We could be generating this directory structure and the module.xml, but puppet-jboss_admin already do it.

Alternatively, we can deploy_from_url { 'https://jdbc.postgresql.org/download/postgresql-9.4-1201.jdbc4.jar': }. It used to be problematic in JBoss AS 7.

**Comment by biemond** [comment]
maybe we can use only if or unless on the exec to know the current state, this won't show up. So wildfly-cli-wrapper and deploy.rb script should support the retrieval of a object status.

Ok is there a public place where we can download this tar.gz file

Thanks again

**Comment by jairojunior** [comment]
@biemond the problem is that if we have an unless script and a command script, performance will be degraded cause we'll need to connect and send a query/operation to JBoss-CLI twice instead of only once. It's a trade-off that I'm trying to balance and I've been discussing with puppet-jboss_admin creator.

This wildfly page recommends to deploy JDBC Driver as a regular file: https://docs.jboss.org/author/display/WFLY8/DataSource+configuration?_sscc=t

Maybe we could give it a try and deploy from URL or Nexus. We could also improve module installation process in a way that it downloads a JAR artifact from Nexus and creates a directory structure and module.xml based on GAV information.

Something like:

install_module { ''org.postgresql:postgresql:9.4-1201-jdbc41': }

And it will download http://central.maven.org/maven2/org/postgresql/postgresql/9.4-1201-jdbc41/postgresql-9.4-1201-jdbc41.jar and put in $modules_dir/(group id, i.e. org/postgresql)/main with a module.xml based on a template (https://docs.jboss.org/author/display/MODULES/Module+descriptors)

Not sure if you're familiarized with JBoss Modules, but it's related to how JBoss Classloader works.

**Comment by biemond** [comment]
Ok but now you only invoke it twice on the first time ( and that is not a problem )  so the second time only the unless script is executed just like the current situation.

That would be cool if we do the recommended way for the jdbc module.

**Comment by jairojunior** [comment]
You're right. I'll make this change this weekend. =)

**Pull request merged**
