### PR TITLE
Add OS package install option

### PR DESCRIPTION
**Pull request by zipkid**
Add an option to  install Wildfly from an OS package Vs from downloaded tar

### CODE REVIEW

**Comment by jairojunior** [comment]
Hey @zipkid, this is pretty much the code in PR #137 

Do you know @jstremick ?

I suppose the same suggestions I gave there applies here:

- remove install_method parameter and use package if it's provided and URL otherwise
- remove code to set ownership of wildfly directory. I believe it's package responsability.

What do you think?

**Comment by zipkid** [comment]
@jairojunior any thoughts on this?

**Comment by jairojunior** [comment]
The fourth comment is mine. @coveralls is kind of annoying. :smile:

**Comment by zipkid** [comment]
Damn... I missed yours in the forest....
I'll look into your comment :-)

**Comment by zipkid** [comment]
Your comment makes complete sense.
I hope to be able to modify my code according to that soonish...

**Comment by jairojunior** [comment]
Awesome. Feel free to disagree though, it's just a suggestion based exclusively on code review. :smile:

**Comment by jairojunior** [comment]
Awesome. Thanks.

**Pull request merged**
