### PR TITLE
[Has Questions] Update nondestructively

### PR DESCRIPTION
**Pull request by TronPaul**
I've tested this with both recursive and non-recursive updates locally. It does work, however there are some wrinkles with certain types of resources. For example the XA Datasource Properties resource does not allow updates at all. All changes must be made destructively. This means I need a way to specify that a resource or sub-resource should be changed destructively.

My first thought would be to add some sort of parameter that specifies a path for which the resources which match are treated destructively, but that doesn't seem so great. I wanted to put what I had as a PR and see how other people think destructive updates should be treated.

### CODE REVIEW

**Comment by TronPaul** [comment]
As an example of the destructive paths bit.

```
wildfly::util::resource { '/subsystem=datasources/xa-data-source=DefaultPool':
  content => {
    'driver-name' => 'oracle',
    'jndi-name'   => 'java:/jdbc/DefaultPool',
    'operation'   => 'add',
    'password'    => 'password',
    'user-name'   => 'undef',
    'xa-datasource-properties' => {
      'url'  => 'jdbc:oracle:thin:@DEFA'
    }
  },
  destructive_paths => ['/xa-datasource-properties']
}
```

**Comment by TronPaul** [comment]
Should solve #54 though I didn't use an `update-properties` operation since I didn't see an operation on https://docs.jboss.org/author/display/WFLY8/Global+operations

**Comment by jairojunior** [comment]
I'll try to answer everything (in an unordered way) in this single comment and it might get confusing, but here it goes:

* Unfortunately only a few subsystems have `update-properties` (e.g. `/subsystem=logging/periodic-rotating-file-handler=FILE:update-properties(...)`) and a composite operation of `write-attribute` is indeed a more generic solution.

* Are you sure XA Datasources doesn't support hot changes? Maybe if you disable it and remove any dependencies it has you'll be able to change.

* My main concern is more related to the case above (you need to disable a resource in order to change it) and deployments dependencies on resources, so if you have, for example, an EAR that depends on a datasource, a queue and a remoting connector, you won't be able to perform some changes in theses resources while the deployment is up (even with write-attribute). [1]

[1] In practice I've seen two ways to realize this: (1) change configuration XML (i.e. offline changes) or (2) disable deployment, change resources and enable it again. Both alternatives imply in a small downtime, and it might be related to JBoss AS 7+ architecture (subsystems are lazily loaded).

* Your PR is a big step towards #54 (and definitely solves cases where there is no dependency involved), but I still can't see how we are going to implement more complex scenarios using just Puppet. Lately I've been thinking that you should use an orchestration tool (MCollective, Capistrano, Fabric, CFEngine) in conjunction with Puppet to perform operations that will put you in the desired state. What do you think? Are we able to put this dependency resolution intelligence in our custom types or is it too application-specific?

Thank you for your contributions. I'll merge them and perform some tests as soon as possible.

**Comment by TronPaul** [comment]
The XA Datasource does support hot changes, but the XA Datasource Property resource ie `/subsystem=datasources/xa-data-source=DefaultPool/xa-datasource-properties` must be updated via a remove and a recreate. Wildfly does not let you edit their value. I'm working on some changes for enabling destructive updates for resources/subresources since they're needed for us. I'll put a PR for those changes when I finish them.

**Comment by TronPaul** [comment]
Turns out you can't remove properties while the datasource is enabled.
```
Error: Failed with: JBAS014653: Composite operation failed and was rolled back. Steps that failed:Operation step-1JBAS014762: Removing services has lead to unsatisfied dependencies:
==> fbstandalone: Service jboss.xa-data-source-config.DefaultPool.xa-datasource-properties.URL was depended upon by service jboss.xa-data-source-config.DefaultPool for {"address":[],"steps":[{"address":[{"subsystem":"datasources"},{"xa-
data-source":"DefaultPool"},{"xa-datasource-properties":"URL"}],"operation":"remove"},{"address":[{"subsystem":"datasources"},{"xa-data-source":"DefaultPool"},{"xa-datasource-properties":"URL"}],"value":"jdbc:oracle:thin:@DEFB","operati
on":"add"}],"operation":"composite"}
```

**Pull request merged**
